DO
$$
BEGIN

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_NAME = 'songs' and COLUMN_NAME = 'genre') THEN
    ALTER TABLE songs
        ADD COLUMN genre text DEFAULT NULL;
END IF;

END;
$$