DO
$$
BEGIN

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME = 'fk_friends__friend_id') THEN
    ALTER TABLE friends DROP CONSTRAINT fk_friends__friend_id;
END IF;

END;
$$;