DO
$$
BEGIN

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME = 'fk_songs__creator_id') THEN
    ALTER TABLE songs DROP CONSTRAINT fk_songs__creator_id;
END IF;

END;
$$;